---
title: "Energy Law: Electricity & Resources"
authors:
  - name: "PID: 720006810"
abstract: |
  This is a submission for the final examination in the Fall 2020 iteration of UNC School of Law's course entitled Energy Law: Electricity and Resources (LAW 489.001).
bibliography: law_references.bib
csl: unfccc.csl
# nocite: '@*'
number_sections: true
output: 
  rticles::arxiv_article:
    keep_tex: true
---

# Local Electric Utility v. Power From Poop
\label{sec:question_1}

**Q**: A new company, Power From Poop (PFP), has developed an electric generator that converts hog waste to electricity. The process can produce enough electricity to power an entire hog farm using only manure stored at the farm. PFP recently entered into a financing agreement with the owner of Happy Hog Farm whereby PFP installs the generator at the farm, owns and maintains the generator, and provides electricity to the farm. In exchange for the electricity, the owner of Happy Hog Farm pays PFP a monthly fee. The fee is based on the estimated savings on Happy Hog’s monthly electricity bill. (In other words, the fee is roughly the amount that Happy Hog would pay to local electric utility if PFP did not install the electric generator.) All electricity produced by PFP is consumed at the farm (meaning electricity generated by PFP does not enter the local electric utility’s grid). According to the agreement, PFP retains ownership of the equipment used to generate the electricity.

The local electric utility sues, claiming that PFP is operating as a “public utility” in violation of state law. The relevant law defines a “public utility” as any entity that sells electricity “to the public.” The law allows property owners to generate their own electricity on-site, but the law does not specify whether this exemption applies when the property owner does not also own the electric generator. If the court finds that PFP is a public utility, state law would prohibit PFP from selling electricity to Happy Hog Farm because the farm is located within the exclusive service territory of the local electric utility. PFP argues that its actions do not fall within the definition of a “public utility.” 

**You are clerking for a judge who will hear the local utility’s lawsuit. Draft a memo for the judge that (a) explains the rationale for exclusive service territories, (b) explains how other courts have addressed similar questions about what qualifies as a public utility, and (c) recommends how she should rule in this case. Explain your reasoning.**


**A**: (word count: 1242)

## Rationale for Exclusive Service Territories

Public utilities are charged with universal service to the public in exchange for monopoly power in a fixed service territory. The legal basis for this arrangement arises from common law precedent involving common carriers such as ferry and bridge operators, and has been refined throughout the past and current century largely in the context of energy law.

The fundamental rationale for the state to offer exclusive access to a single provider for its energy provision is that this right is commensurate with the service it has requested of this provider.

When the state takes over an industry that is naturally prone to monopoly and imposes a structured monopoly, it usually does so for the sake of efficiency and equity. Rather than engaging in the competition and creative destruction of building multiple electricity grids only to end up with a profit maximizing monopolist who will not serve all comers, there is efficiency to be had in designing and regulating a monopolistic system that can work for everyone.

More specifically, in order to secure the capital required to build and operate an energy network in an affordable and efficient manner requires the predictibility and focus of an exclusive monopoly franchise. The returns are not tremendously high for the amount of money required to build everything, and without a guaranteed customer base the endeavor would be considered high risk [@crossReturnEquitySurvey2014]. In turn, this would lead to higher rates for consumers.

Providing the utility with exclusive access to a fixed territory unlocks the utility's business model to meet consumers' needs and provides the state with a freedom (or right) to request (or require) high quality service. The state is getting quite a lot: the utility has a duty to serve all comers at just and reasonable rates [@MunnIllinois1877]. In return the utility is entitled **but not obligated** to a fair return on its investments [@SmythAmes1898; @BluefieldCoPub1923]. If an investment is not ultimately useful to the consumers within the franchise, its cost recovery may not be allowed [@JerseyCentPower1987; @DuquesneLightCo1989].

Exclusivity itself is a double-edged sword. In *Tripp v. Frank* the court denied a ferry service's claim of broad exclusive power along the river's routes and established that the rights of an exclusive service provider "must be commmensurate with [its] duty" [@TrippFrank1792]. This principle has held for other monopolies on like-technologies with geospatial and time-based franchise rights, such as bridges built closely to each other under competing franchisees on behalf of the state's interest in allowing commerce between municipalities [@ProprietorsCharlesRiver1837]. Likewise, when new technologies allow individuals to acquire the end result they desire through a different means, there is no right to prevent them from transitioning to this new method (e.g. from streetcars to automobiles [@MarketStRailway1946]).

Exclusivity has been refined in the context of fossil gas and electricity regulation in the United States, often in diverging ways depending on which fuel type is being used [@lazarElectricityRegulationUS2016]. There have also been converging or lagging similarities between the approaches to these fuels over time and across stages of the energy use life-cycle [@gilstrapUnitedStatesElectricity2015].


## Decisions in Similar Cases

Generation of energy for self-consumption is unequivocally allowed by law in this case. so we are left with the question of whether this transaction constitutes the sale of power.

In *State ex rel. Utilities Comm’n v. North Carolina Waste Awareness and Reduction Network* the court held that a behind-the-meter arrangement involving a third-party owner of the solar system was a sale of power [@StateNcWaste2017]. However, in this case the system was connected to the grid to engage in net metering with the local utility and the payments to the third party were directly tied to the production of electricity. It is not clear that a case without these attributes would have the same outcome.


*PW Ventures, Inc. v. Nichols* held that a firm wishing to offer a take-or-pay contract for heat and power to a large industrial facility was a public utility, which addresses a case in which net metering is not at issue [@PWVenturesInc1988]. However, again the contract in question is based directly on the quantity of energy delivered which speaks to a direct transaction for energy. Furthermore, this decision rests heavily upon a speculation that allowing such transactions might lead to a breakdown in the utility regulatory contract, with more large industrial consumers opting to procure energy behind the meter. This logic is circular, especially given the aforementioned limitations on the scope of franchise rights. Ultimately, this decision rests soundly on a finding that the transaction is a sale power and that the seller is acting as a public utility. There is little indication that this finding would be justified only on the basis of a risk to utility business models from transactions that were defined otherwise (such as equipment leases of energy efficiency measures, or loans to support money saving retrofits).


In *Sz Enterprises, Llc v. Iowa Utilities Bd.* the court takes a more measured approach by using an eight-factor test to determine whether the nature of the transaction being contemplated qualifies as a sale of power [@SzEnterprisesLlc2014]. In this case involving behind-the-meter solar which does not feed back into the local utility's system, the court finds that such an arrangement does not constitute the actions of a public utility even though the payments are directly tied to the production of the system. This finding primarily relies on the fact that the power system is not dedicated to public use, that the provider does not intend to monopolize the customers' energy use (they are still connected to the utility after all), and that the provider does not accept substiantially all requests for service.

Even if this transaction is classified as a sale of power by logic or fiat, there is still the question of whether this is a wholesale or retail transaction. This has implications for jurisdition between the Federal Energy Regulatory Commission (FERC) and state public utility commissions (PUCs).

It is not obvious that the action being taken is a retail transaction. Power From Poop (PFP) is offering Happy Hog Farm (HHF) access to technology that can help it moderate its participation in other enery markets such as the electricity and methane markets. In fact, were this utility located in an RTO it would be required to compensate these farms in addition to their savings to the extent that this type of arrangement can add value to the grid operations through decreased peak load and other demand response services. This type of transaction has been classified as wholesale by FERC and upheld supreme court review [@FercElectricPower2016]. If the transaction is classified as a sale of power, the project may have rights as a Qualifying Facility under the Public Utility Regulatory Policy Act (PURPA) [@PublicUtilityRegulatory1978].

## Recommendation

The transaction contemplated by PFP and HHF is not a sale of power and PFP is not acting as a public utility. PFP is not holding itself to all the public with its service, or attempting to monopolize HHF's energy supply. HHF will even remain connected to the utility's grid as the transaction occurs. The terms of the transaction are based on the expected savings on the farm's bill, not actual savings dependent on actual production. Under the principles and precedents listed above, a transaction based on the actual energy savings (rather than the actual production) might not even be considered a sale of power. Even transactions with performance guarantees tied to generation are allowed under the strictest of regulatory regimes.


\newpage
# Fossil Gas GenCos v. East Carolina
\label{sec:question_2}

**Q**: The state of East Carolina restructured its electricity sector in 2005. As a result, numerous companies built new natural gas-fired power plants in the state. Other companies own coal-fired power plants. All power plants in the state participate in a competitive, interstate wholesale electricity market managed by a regional transmission organization (RTO). The RTO manages a wholesale electricity market covering 5 states. Low natural gas prices are making it difficult for coal-fired power plants and nuclear power plants to compete in the RTO market. Some coal-fired power plants in East Carolina have already retired because they could not successfully compete with the newer, more efficient natural gas-fired power plants in the region. Other coal-fired power plants have announced that they will retire by 2022 if wholesale electricity prices do not increase. 

Legislators in East Carolina fear that losing more coal-fired power plants will jeopardize the electric grid’s reliability.  They pass a new law that requires the state government to purchase “State Reliability Credits” from coal-fired power plants located within the state. According to the law, the cost of the State Reliability Credits will fluctuate depending on the RTO’s wholesale electricity prices. If wholesale prices are high, the state will pay less for the State Reliability Credits. If wholesale prices are low, the state will pay more for the State Reliability Credits. The additional revenue from these credits will allow the state’s remaining coal-fired power plants to remain in operation.

A coalition of companies operating natural gas-fired power plants opposes the new state law and challenges the law in court. **In your opinion, is a court likely to uphold the state law? Why or why not? Are there alternate strategies that state officials could implement to support coal-fired power plants within the state? If so, describe the other strategies and identify any legal vulnerabilities.**

**A**: (word count: 702)

## Will the Law Stand?

The biggest risk borne by this law is that it discriminates among those generators eligible for compensation directly by their location inside or outside of the state. It is usually acceptable to discriminate among generators connected to the state's distribution systems in determining state resource goals, but to do so at the transmission level (which presumably any power plant in this case would be) opens the law up to a challenge under the dormant commerce clause. FERC has jurisdiction over these interstate wholesale transactions [@PubUtilComm1927; @FPCSouthernCal1964] and has given the market operating power to the RTOs through FERC Order 2000 [@FERCOrder20002000], so unless there is a compelling reason otherwise there will be preference toward its regulations when they are directly affected by state policies [@FercElectricPower2016]. Specifically, we must apply the three-part Pike Test to determine whether a policy of this nature is justified.

1. **Is the law extraterritorial?** No, the law does not explicitly direct the behavior of actors in other states. Therefore, we move onto part two.

2. **Is the law discriminatory?** Yes, the law is facially discriminatory in that it only pays generators in East Carolina. Therefore, we must apply a strict scrutiny to this policy as it affects interstate commerce in an intentionally discriminatory fashion. Is there a legitimate state interest in discriminating in this way? The only state interest mentioned is the legislators' fear of diminishing grid reliability from less coal capacity on the system. However, this fear does not seem to be held by the RTO, which is the entity charged by FERC with actually making such a technical determination if true for the grids in all of its member states. Presumably the RTO is aware of the pending retirements of these plants and changing makeup of the generator mix, and has incorporated this knowledge into designing and maintaining its market mechanisms. Therefore, there is not a legitimate state interest in discriminating by the state of origin of the power being compensated, and the law will not stand.

3. **Is there a burden on interstate commerce?** Although the result of step two results in the application of strict scrutiny and presumably in the invalidation of the law, if a legitimate interest is found then this interest must be balanced against the burden on interstate commerce. Given that no legitimate state interest is presented, I will not speculate here other than to mention this steps as a final stage of the Pike Test.

## Alternate Strategies

There are a number of alternate strategies that the state can pursue if this law is not viable. First, the state can use its resources to pay directly for the power from the desired plants. There is no question this is legally viable, although it may be considered politically or fiscally imprudent. Second, it could broaden the scope of the credits to include out-of-state generators and a wider scope of fuel types, akin to New York's Zero Emissions Credit scheme which passed court scrutiny through its specific design [@CoalitionCompetitiveElectricity2018]. In *Hughes v. Talen* the court found that Maryland's compensation mechanism for in-state generators was invalid because of its direct affect on wholesale markets [@HughesTalenEnergy2016]. However, East Carolina does not require participation in wholesale markets as part of this law, merely pegging the price to their prices. A power plant could presumably ground its power and still be paid under the program. Even so, the court has found that such indirect mechanisms can still be considered to interfere with wholesale transactions depending on the precise structure [@FercElectricPower2016], so redesigning this policy to to ignore state boundaries could still fail further scrutiny. Third, the state could consider securitization and retirement of its coal fleet, which involves ratepayer and shareholders of the utility prematurely writing down the assets in question and paying for this write-down over time through rates. This method is open to criticism that the assets are were imprudently constructed if they are not being utilized. Though this concern rarely takes precedence when the change is due to external policy or factors outside of the utility's control, it has applied in contexts where the utilities overbuilt certain types of resources that were no longer considered safe or desireable for the state [@JerseyCentPower1987; @DuquesneLightCo1989].


\newpage
# TarHeel Energy Rate Case
\label{sec:question_3}

**Q**: TarHeel Energy is a monopoly electric utility operating in a state with a traditional regulatory structure. According to the utility’s analysis, electricity demand in the area is expected to grow significantly over the next decade. A local nonprofit organization has commissioned its own analysis that concludes electricity demand will not increase for the foreseeable future. TarHeel Energy is able to meet current electricity demand, but will need additional generation if electricity demand increases.

TarHeel Energy has announced plans to build a new type of nuclear power plant to meet the projected increase in electricity demand. According to the utility, this new type of nuclear power plant is safer, produces less waste, and is cheaper to operate than a conventional nuclear power plant. The estimated construction cost is $5 billion. If TarHeel Energy completes this project, it would be the first power plant of its kind. 

State law allows the Public Utilities Commission (PUC) to increase electricity rates prior to the completion of a new nuclear power plant to help cover planning and construction costs (referred to as Construction Work in Progress, or CWIP). The utility will request a CWIP rate increase that will raise electricity bills approximately $100 per year for the average household. The utility will not move forward with the project unless the PUC approves the CWIP rate increase. The utility also has other options for new electricity generation, including natural gas and various forms of renewable energy.

## 3(a) {-}

**Based on your understanding of current factors affecting electricity sector decision-making, what arguments could the utility make in support of its plans to build a new nuclear power plant?**

## 3(b) {-}

**You are a commissioner on the state’s PUC. Based on the facts presented here, would you approve the CWIP rate increase? Why or why not?**

## 3(c) {-}
Assume your state legislature is debating a bill to enact a Clean Energy Standard that would require 100% carbon-free electricity generation by 2040. The state’s current generation mix is approximately 50% carbon-free (a combination of renewable energy and existing nuclear power plants). **You are still a commissioner on the state’s PUC. Would this new law influence your decision about the CWIP rate increase? Why or why not?**

## 3(d) {-}
Now assume the PUC did approve the CWIP rate increase. The utility started construction, but a change in market conditions prevented the utility from completing the project. The utility spent $2 billion before deciding to cancel the project. Prior to announcing the cancellation, the utility recovered $500 million through the CWIP rate increase. The PUC must determine whether the utility may recover the remaining costs through electricity rates, or whether the utility’s shareholders should be responsible for some or all of the costs for the unfinished power plant. **As a PUC commissioner, how would you allocate the planning and construction costs? Explain your decision and identify any legal and economic factors that you would consider.**


**A**: (word count: 671)

## Arguments in Favor of Proposed Plan

The utility may argue that these construction costs are prudent, just, and reasonable expenses toward servicing the customer as they are required to do. If demand increases, new generation will be needed and if it is lacking may lead to an increase in prices as the system is stressed and imports are required. The levelized cost of energy from nuclear is relatively low compared to other sources of generation, and certainly cleaner at the stack. Given the use of new technology, they may argue that the state's residents will be the first to benefit from this new technology and that the tech may somehow be used to benefit the utility's financial viability by keeping it on the forefront of the changing market rather than falling behind. 


## Commission Approval

As a commissioner I would not approve the rate increase. Applying the end results test [@] suggests that a $100 per year increase in the average users' bill to support a power plant that may or may not eventually exist is unjust and unreasonable. Assuming average bill sizes typical in the United States today, this represents a 5-10% increase in the average bill. This premium will persist for years before the plant is complete, if ever.

There is also reasonable disagreement as to whether demand growth will actually occur, and the commission has not been provided with a comprehensive analysis of why the utility is choosing this plant as its source of new generation among all of its choices. The least-cost mandate suggests that commisions look at all of the available choices together, not one at a time. An investment based on this type of speculation about growth without considering all of the available options could be considered imprudent.

## Impact of Proposed Clean Electricity Standard

Since the bill is still being debated, it is harder to incorporate it into commission decisionmaking than if it had become law. However, the bill does does show intent and trend from lawmakers, and it would be fair to infer that legislative risk is likely in favor of more clean energy than less. In that context, it may not be a good idea to make a large decision about the composition of the state's electricity generation mix until there is more certainty about the structure of the program. It could even benefit the utility's financial viability and competitiveness to wait for a solid price signal for clean energy. Keep in mind that even a clean energy standard could be implemented in a way that prefers to keep existing nuclear and incent new renewables and storage, rather than incenting new nuclear.

This new information would further convince me to deny the utility's request to decrease the diversity of the grid with a cherry-picked project, instead favoring a comprehensive plan that compares all of the options in the context of dynamic policy and market risks.


## Hypothetical Project Cancellation

Considering the three factor test to determine the fair return on invested capital of a pubic utility, I would vote to allocate the remaining $1.5b construction costs to utility shareholders. Primarily, this would rely on the arguments put forward during my vote to deny the CWIP in the first place, and those of them which came to pass (changing market conditions). The plant is not used or useful to the ratepayers and they have already paid $500m for the privelege of maybe having such a plant on the grid, but the utility did not hold up its end of the bargain.


For a typical utility as this is assumed to be, this $1.5b cost is not so significant as to threaten its financial integrity. As long as the overall revenue requirement is met for ongoing service and the construction of needed generation, the shareholders should have had the expectation that the speculative new plant might not reach completion. This is a risk that they expected to bear, and therefore they have been justly compensated for it. Furthermore, it is dangerous to encourage the moral hazard that comes from allowing shareholders to allocate performance risk to ratepayers. As the steward of the regulatory construct, the PUC has an obligation to draw a line when the utility does not meet its obligations.


\newpage
# References^[All sources are from the course materials including those cases and resources cited by @eisenEnergyEconomicsEnvironment2019.] {-}

