---
title: "LEAD Aggregation"
author: "Eric Scheier"
date: "10/16/2020"
output: html_document
---

```{r setup, include=FALSE}
is_final=FALSE
is_preview=TRUE
is_draft=TRUE
set.seed(123)

knitr::opts_chunk$set(comment='##', 
                      collapse=ifelse(is_preview,TRUE,!is_draft),
                      echo=ifelse(is_preview,FALSE,is_draft),
                      eval=TRUE,
                      warning=ifelse(is_preview,FALSE,is_draft),
                      error=ifelse(is_preview,FALSE,is_draft),
                      results=ifelse(is_final,'hide',ifelse(is_preview,'hide','asis')),
                      fig.keep='all',
                      message=ifelse(is_preview,FALSE,is_draft),
                      include=ifelse(is_preview,TRUE,is_draft),
                      tidy=TRUE,
                      cache=FALSE,
                      fig.margin=FALSE,
                      fig.fullwidth = FALSE
                      )
```

```{r include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
kable(knitr::opts_chunk$get() %>% enframe())
```


```{r}
library(sf)
library(MASS)
library(scales)
library(caret)
library(spatstat)
library(GGally)
library(ggpubr)
library(patchwork)
library(mgcv)
library(tidyselect)
library(RColorBrewer)
library(wesanderson)
library(tigris)
library(readxl)
library(tidyverse)
# library(viridis)
source("lead_munging.R")
source("charts.R")
```

```{r}
states <- "all" #c("nc","ca") #  "nc" #c("nc","sc" ,"ca") # 
income_metric <- "fpl15" #"ami68" #
geographic_scope <- "tract" #statecitycounty
format <- "lead" #"replica" # 
refresh <- FALSE

lead_lead <- get_multiple_states(states=states,
                                income_metric=income_metric,
                                geographic_scope=geographic_scope,
                                refresh=refresh,
                                format=format)
# write_csv(lead_lead, "lead_ami.csv")
```

