---
title: "Leaflet"
author: "Eric Scheier"
date: "10/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=FALSE}
library(choroplethr)
library(choroplethrMaps)
```

```{r eval=FALSE}
library(rgdal)
library(leaflet)
library(sf)

cntr <- centroids %>% apply(2,mean)
zoom_level <- 10
# from nikhil kaza
# https://nkaza.github.io/post/exploratory-data-analysis-visualisation/
# Because the presence of 0's create a problem for quantiles (some of the quantiles are the same) let's separate them out while calculating breaks.

# st_crs(tract_shp)
tract_shp <- st_transform(tract_shp, crs =4326)

Qpal <- colorQuantile(
  palette = "Reds", n = 5,
  domain = tract_shp$metric_median[tract_shp$metric_median>0]
)


labels <- sprintf(
  "County: %s <br/> AQI>100 days: <strong>%s</strong> %%",
  paste(tract_shp$GEOID, 
        tract_shp$STATEFP, sep=","),prettyNum(tract_shp$metric_median, digits=2)
) %>% lapply(htmltools::HTML)

m <-  leaflet(tract_shp) %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
   addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
       addPolygons(color = "#CBC7C6", weight = 0.25, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
             fillColor = Qpal(tract_shp$metric_median),
              highlightOptions = highlightOptions(color = "green", weight = 2, bringToFront = TRUE),
             label = labels,
             labelOptions = labelOptions(
               style = list("font-weight" = "normal", padding = "3px 8px"),
               textsize = "15px",
               direction = "auto"),
             group = "Tracts"
             )%>%
  addLayersControl(
    overlayGroups = c("Tracts", 'Basemap'),
    options = layersControlOptions(collapsed = FALSE)
      )  %>% 
  setView(cntr["X"], cntr["Y"], zoom = zoom_level)

  
m 
```

